### ISSUE TITLE
"0" is converted as empty string ""

### ISSUE THREAD

**Issue by JoniJnm** [MirazMac/DotEnvWriter#1]
Hi, thanks for the useful library

I found a bug. "0" is converted as empty string due the `empty()` usage in `escapeValue` function

https://github.com/MirazMac/DotEnvWriter/blob/ee9528cc9916318edc17c9fe223995ca78908f9d/src/Writer.php#L264-L268

Due $value is a string, maybe it just should be:

```php
if ('' === $value) {
    return '';
}
```

**Comment by MirazMac** [comment]
Thanks for reporting, I've fixed this in 0.2.
